- name: Install nvm
  hosts: localhost
  vars:
    version: '{{ nodejs.version|default("lts")|lower }}'
    version_text: "{% if 'lts' == version %}LTS{% else %}v{{ version }}{% endif %}"
    nvm_version: '{{ nodejs.nvm_version|default("0.39.1") }}'
  tasks:
    - name: 'Install nvm v{{ nvm_version }}'
      shell: 'curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v{{ nvm_version }}/install.sh | bash'
      args:
        creates: /home/{{ ansible_user_id }}/.nvm/nvm.sh

    - name: 'Install NodeJS {{ version_text }}'
      vars:
        version_arg: "{% if 'lts' == version %}--lts{% else %}{{ version }}{% endif %}"
      shell: '/bin/bash -c "source ~/.nvm/nvm.sh && nvm install {{ version_arg }}"'
      args:
        creates: /home/{{ ansible_user_id }}/.nvm/alias
