- name: Install nvm
  hosts: localhost
  vars:
    version: '{{ nodejs.version|default("lts") }}'
    nvm_version: '{{ nodejs.nvm_version|default("0.39.1") }}'
  tasks:
    - name: 'Install nvm v{{ nvm_version }}'
      shell: 'curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v{{ nvm_version }}/install.sh | bash'
      args:
        creates: /home/{{ ansible_user_id }}/.nvm/nvm.sh

    - name: 'Install NodeJS v{{ version }}'
      shell: '/bin/bash -c "source ~/.nvm/nvm.sh && nvm install {{ version }}"'
      args:
        creates: /home/{{ ansible_user_id }}/.nvm/alias
