---
- name: Install Nginx Server
  hosts: localhost
  become: yes
  tasks:
    - name: Install Nginx Server
      apt:
        name: nginx
        state: latest

    - name: Enable nginx server service
      ansible.builtin.service:
        name: nginx
        enabled: yes
        state: started
      when: 'wsl == false and nginx.enable_service == true'
